spring.application.name=RoboAssistente

telegram.bot.token=8913196887:AAHziFu_TcxkbpyfCNRoIDz_i2ndoglg8A4
telegram.chat.id=8788266264
brapi.token=fs7WNe42TZmmtXLkeD7Dy2
brapi.url=https://brapi.dev/api/quote

spring.datasource.url=jdbc:h2:mem:robodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console