spring.application.name=RoboAssistente

telegram.bot.token=8913196887:AAHziFu_TcxkbpyfCNRoIDz_i2ndoglg8A4
telegram.chat.id=8788266264
brapi.token=fs7WNe42TZmmtXLkeD7Dy2
brapi.url=https://brapi.dev/api/quote
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=